### ISSUE TITLE
Doesn't compile on Mac / clang

### ISSUE THREAD

**Issue by pedro-w** [grrk-bzzt/kq-fork#102]
Some errors here and elsewhere from ce01e005 I think.
https://github.com/OnlineCop/kq-fork/blob/76d3fe1b068d8fd9ccf8b7670b47ccbe96361476/src/tiledmap.cpp#L682

```
kq-fork/src/tiledmap.cpp:682:58: error: expected
      '(' for function-style cast or type construction
                unsigned int index = std::clamp(unsigned int(i + zone.x ...
                                                ~~~~~~~~ ^
1 warning generated.
kq-fork/src/entity.cpp:546:47: error: expected '(' for
      function-style cast or type construction
        int dest_tile_x = std::clamp(unsigned int(source_tile + dx), 0U...
                                     ~~~~~~~~ ^
kq-fork/src/entity.cpp:547:47: error: expected '(' for
      function-style cast or type construction
        int dest_tile_y = std::clamp(unsigned int(source_tile + dy * g_m...
                                     ~~~~~~~~ ^
1 error generated.
```

**Comment by OnlineCop** [comment]
Ah; I probably need to `static_cast<unsigned int>(...)` those instead of the C-style casts.

**Comment by pedro-w** [comment]
Also, (sorry to be the bearer of bad news)
```
Undefined symbols for architecture x86_64:
  "KZone::ZONE_NONE", referenced from:
      tmx_map::set_current() in tiledmap.cpp.o
ld: symbol(s) not found for architecture x86_64
```

missing #include zone.h ? No, actually I don't know what's up with this

**Comment by pedro-w** [comment]
OK, `static constexpr int ZONE_NONE = 0;` in zone.h:7 fixes it for me.

**Comment by OnlineCop** [comment]
I'd expect `#include "zone.h"` should fix that, since that's where that's defined.

**Comment by OnlineCop** [comment]
`static const int ZONE_NONE = 0;` to `static constexpr int ZONE_NONE = 0;` then?

**Comment by OnlineCop** [comment]
Do I also need those `#include "zone.h"` anywhere as well?

**Comment by pedro-w** [comment]
That works for me if it works for you.  zone.h is included indirectly (tiledmap.h) so no more includes needed

**Comment by OnlineCop** [comment]
Fix pushed: #103

**Comment by pedro-w** [comment]
#103 fixed the ZONE_NONE and tiledmap.cpp but unfortunately not the casts in entity.cpp, lines 546 and 547.

**Comment by OnlineCop** [comment]
A lot of these casts are Band-Aids that one of my upcoming PRs is trying to address: I'd like to do something like `KMap::Coords(tile_x, tile_y)` which will take the map's `.xsize` or `.tilex` or whatever it's named, and clamps between 0 and `g_map.xsize*g_map.ysize-1` so we don't accidentally multiply by `.ysize` again (#81).
