### ISSUE TITLE
Death and Doom spells don't work

### ISSUE THREAD

**Issue by z9484** [grrk-bzzt/kq-fork#109]
They don't work when the player casts them and don't seem to do anything when the npc's casts them as well.

**Comment by pedro-w** [comment]
I can look into this. Do you know when they stopped working?

**Comment by z9484** [comment]
Hmm since at least before April so I would guess quite a while ago.

**Comment by pedro-w** [comment]
I can reproduce; when casting Doom the wobbly grey skull effect appears but no damage is done. I can't yet see where in the logic this is going wrong - the fact it affects both player and NPC casts must be a clue.

**Comment by pedro-w** [comment]
I went right back to revision 4 of the subversion repo on sourceforge, which is the earliest code I could access. Unless I'm missing something, Doom didn't do anything there either. You see the skull effect, then the spell can miss or, if it hits, no damage indicator shows and no damage is done. It's supposed to take 3/4 of the opponent's HP, I believe.
I haven't looked at Death.
