### ISSUE TITLE
move_entity issues

### ISSUE THREAD

**Issue by z9484** [grrk-bzzt/kq-fork#111]
Move entity and set_ent_active don't seem to be working after some recent commits.
From the save file: Just go north into the cave. Talk to Binderak and select second option. See cave8.lua
https://gist.github.com/z9484/d50ad51a482b832b7f645c9e5f354571

**Comment by pedro-w** [comment]
Ironically I think was fixing the bug referenced here https://github.com/OnlineCop/kq-fork/issues/81#issuecomment-1159330965 that caused this. `copy_map` creates a map with -1 for every cell containing an obstacle and every cell containing an ent. This includes the one we're supposed to be finding a path for, so on the very first iteration of `search_paths` it finds its way blocked by itself, and the whole thing stops. 
Previously the cells containing ents were calculated incorrectly so they weren't blocked.
The solution probably is to reset the square under the ent that's moving to 0 before calling `search_paths` but I haven't tried that.

**Comment by pedro-w** [comment]
Something like
```
diff --git a/src/movement.cpp b/src/movement.cpp
index 6c4af05..a174389 100644
--- a/src/movement.cpp
+++ b/src/movement.cpp
@@ -183,6 +183,7 @@ int find_path(size_t entity_id, uint32_t source_x, uint32_t source_y, uint32_t t
     }
 
     copy_map(map);
+    map[Game.Map.Clamp(source_x, source_y)] = 0;
     uint32_t result = search_paths(entity_id, map, 1, source_x, source_y, target_x, target_y, 0, 0,
                                    Game.Map.g_map.xsize, Game.Map.g_map.ysize);
```
seems to work at first glance. But all that code may benefit from an overhaul as it's using char* and malloc and stuff.
