### ISSUE TITLE
Timings for damage indicators (outstanding from SDL conversion)

### ISSUE THREAD

**Issue by pedro-w** [grrk-bzzt/kq-fork#118]
I haven't got a working binary of the Allegro version but I think the timing of the damage indicators over the characters heads during combat is now different (they used to be visible for longer?)
Is this correct?

**Comment by z9484** [comment]
Yes I did this to make combat run faster. I messed with the combat sleeps to make combat feel more responsive.

**Comment by pedro-w** [comment]
Oho, OK, I thought I'd messed something up! As you were.
