### ISSUE TITLE
Convert maps to the TMX format.

### ISSUE THREAD

**Issue by grrk-bzzt** [grrk-bzzt/kq-fork#12]
TMX is a standardised file format used by the map editor [Tiled](http://www.mapeditor.org/).

Converting all our maps to TMX will allow us to get rid of the map editor and therefore have less code to maintain while using Tiled for maps creation and modification.

**Comment by peterhull90** [comment]
I've done a bit of work on this, still quite a way to go though (see below.)
![town1tmx](https://cloud.githubusercontent.com/assets/376711/9072535/a3efb7e0-3af3-11e5-9137-d49d0fbba48f.png)

**Comment by OnlineCop** [comment]
Looking good. Is this built off of the town1.tmx file from commit 73543a539f815b3e65a72bb2a3496c78776befba or is this a different version of the map?

**Comment by peterhull90** [comment]
Oh, I didn't know that mapdump could do that. No, it's based on a python
script that loads in a .map file from KQ and outputs a .tmx file. At the
moment it does the three 'graphics' layers, the bounds and the markers (the
last two as object layers in Tiled). It also does entities but only their
position. It doesn't do shadows, zones or obstacles yet. I'm quite hopeful
as the code is a bit long-winded but straightforward (I'm not a python
expert by any means!) When it's done I'll put in a pull request.

**Comment by peterhull90** [comment]
I've made an experimental branch to assess the feasibility of this - and it all looks fairly straightforward. Please see the commit message for the limitations of what has been done.
https://github.com/peterhull90/kq-fork/commits/experimental-tmx-loader

**Comment by peterhull90** [comment]
further to this, I think @OnlineCop mentioned elsewhere about converting some of the game structures to a more 'object oriented' format. I was planning to keep this experimental branch up-to-date with progress on that front then it can be merged at some point. The alternative is to merge this (or some development of it) sooner and change the structures a bit more gradually. Any thoughts?

**Comment by OnlineCop** [comment]
Yes, rewriting the game structure would be both a large undertaking, as well as a necessary one, if we are to be able to support TMX maps.

After we get a consensus on #34, merging the *c_plus_plus* branch to *master*, I would want to have as much conversion to TMX take place sooner than later.

We can rip out a lot of the "debugging" code in the drawing routines as well. That stuff gave the player a way to see zones and obstacles while walking around, which isn't really something we need to keep (and if we did, it would be something we can re-add much later).

**Comment by peterhull90** [comment]
I was thinking the drawing code would need a complete re-write anyway when we change to SDL2.

However another option occurred to me the other day - we *could* keep the A4 drawing model and effectively draw everything onto a 320x240 paletted memory bitmap. Then the only SDL drawing code would be to blit that to an SDL_Renderer once per cycle. That's easy to do.

Did I explain that well enough?

**Comment by OnlineCop** [comment]
I have no experience with SDL (nor with A5) so I would have to defer to others who know how to implement it this way. Reviewing the code, there appears to be a massive amount of palette-specific values that are being referenced everywhere, so as long as either of those can make use of paletted bitmaps, that should be okay. I don't know whether @TeamTerradactyl knows anything about SDL or Allegro5, but if I can get her on board, she might be able to do help out in places that she used to work on (map files, the sprites, etc.).

**Comment by peterhull90** [comment]
I've made more progress on this. The results are in the tmx-loader branch of my fork. 
It would be easiest probably to clone a fresh version of that and see if it works for you.
At the moment not all tilesets are converted but the main map and manor at least are OK. I haven't put in the animations for the sea yet but you'll see Nostik's fires flickering and clocks ticking!
I am loading up the map structures from Tiled then fitting the data into KQ's current map drawing code (including the 8-bit paletted image format). If/when we update the drawing code, that intermediate step could disappear.
Also in general I didn't worry about efficiency, but nothing so far has proved particularly slow.

**Comment by peterhull90** [comment]
Should be closed due to pull request #50
