### ISSUE TITLE
If you press control after loading a game it goes back to the title screen

### ISSUE THREAD

**Issue by z9484** [grrk-bzzt/kq-fork#144]
If you press the turbo/cancel button too soon after loading a game it goes back to the title screen.

**Comment by pedro-w** [comment]
It could almost be a 'feature'! What happens is that it switches to the loaded game within the `KSaveGame::saveload()` loop, and before the loop exits it checks for the cancel key. If pressed, cancel 'wins' and it goes back to the title screen (just as if you'd pressed cancel in the game select list)
