### ISSUE TITLE
If a character's costume has been changed it continues even if you load a different save

### ISSUE THREAD

**Issue by z9484** [grrk-bzzt/kq-fork#145]
During the Ayla side quest, Ayla wears a maid outfit to get into the ritzy part of town. Once the costume has been changed via `set_ent_chrx(hero, 8)` see town5.lua then if a different save is loaded then player 1 will look like the maid no matter which character is number 1. The game has to be restarted to fix it. This is a low priority bug because the time when a character actually has set_ent_chrx set is pretty short so its unlikely to happen.

**Comment by pedro-w** [comment]
Looks like we never actually save or load the `chrx` property, oops. Should be straightforward to add but it won't retrospectively fix any files that were previously saved when Ayla was wearing the costume - she'll be restored just wearing her normal clothes, I think.

**Comment by z9484** [comment]
Hmm I think it should work, because in town5 at least, it calls that script in autoexec so on load it should fix itself. I was wondering why it was called in refresh instead of just called directly, that makes more sense now.

**Comment by pedro-w** [comment]
I've changed my mind; I think it would be sufficient just to make sure chrx for all characters was reset to zero prior to starting a new game or loading an old one. I'll see if that works.
