### ISSUE TITLE
Selling glitch

### ISSUE THREAD

**Issue by z9484** [grrk-bzzt/kq-fork#158]
...

if you have more than one item of the same kind, you can sell them in bulk. If you sell all of them, the item line is still showing. You can keep selling it one at a time (it says 1 of 0).
Actually, I just tested this with a lone item and it also seems to work.
You can then buy something very expensive and keep on selling it until the button breaks down (or you just get tired of it).
It might be in `itemmenu.cpp` in `removeIndex` (or in `remove_item`?).

It reminds me of another one: when you get another character, it's equipment appears also in item list. But it disappears if you sort the list. It might be linked to the previous bug.

...
_Originally posted by @8Gilles8 in https://github.com/OnlineCop/kq-fork/discussions/157#discussioncomment-4450056_

**Comment by 8Gilles8** [comment]
Maybe this could help:
For fun, I just managed to build the old kq lives version from 2007 for my gp2x. I wanted to make a quick cash, but the selling glitch doesn't work there.
The sources I used are [in this archive](https://dl.openhandhelds.org/cgi-bin/gp2x.cgi?0,0,0,0,26,2212) along with an old gp2x version that only works with early firmware (1.4.0).

**Comment by z9484** [comment]
We dropped allegro and switched to libsdl2. Looks like the bug was probably added in that conversion.
