### ISSUE TITLE
Casandra bugs, town2.map

### ISSUE THREAD

**Issue by OnlineCop** [grrk-bzzt/kq-fork#21]
Casandra is displayed in town2, even if you haven't "earned" her. She's also there when you have her in your party:

![image](https://cloud.githubusercontent.com/assets/1168697/2874200/9a3aa8ac-d3db-11e3-89a2-1931189e5c4e.png)

She also looks different in this shot: the NPC image is used to depict her when she's part of the "town entity" logic, but changes to different attire (brown cape vs. white dress) when she's in your party.

**Comment by qubodup** [comment]
Going stp by step: Casandra is in Randen even though you have not rescued her and the Mayor.

So let's reverse-engineer. I use `grep [string] . -iIr` for this a lot to find functions and variables in the kq tree:
1. The substring "thank you for helping" occurs only once: in the function `LOC_join_casandra()` in file `town2.lua`.
2. That function is called only once: in the same file, in the function `entity_handler(en)`. It is called if `entity_handler()` is called with the parameter `13`.
3. `entity_handler()` is defined in C and called when player stands in front of an entity and presses the action key (ALT by default). The parameter is the "Entity number". So now we need to figure out how ids are assigned in Lua code.
4. Only `set_ent_id()` and `set_ent_active()` seem to handle the number 13 in a probably relevant way, both are defined in C but not commented.
5. Both of these get only called if `progress.foundmayor > 0`, which should not be the case.

I don't know how to continue here. It might be that the ID is assigned to the entity in the map file, which as far as I understand is in a binary format.

What would help me is the ability to debug Lua code. Just making `print()` work would be great. I saw some comments about debugging but couldn't figure out what benefits it has and how to activate it.

**Comment by OnlineCop** [comment]
If you open the map editor (I believe it builds under the maps/ directory, called "mapedit") and load a map, hitting F12 turns on the "entities" (NPC) mode. From there, you use up/down or left/right or some other key combination to switch between each NPC in the map.

Yes, the NPCs are embedded in each .map file. So with the Entity mode, it will show you the NPC index value in the bottom-right corner of the editor, which is what you pair up to the .lua files.

There are a few helper files/functions, such as "mapdump" which will spit out the information for each map in a text format: layer values, NPC info, and so forth. That may be of value.

**Comment by qubodup** [comment]
Thanks, it's actually `mapdraw`. I had to
<pre>cd maps
make
./mapdraw town2.map</pre>
Very hard to read (I should just change resolution :) ). Pressing F12 and then navigating with up/down between characters, I could confirm that Casandra is id 13. `mapdump` is interesting and it seems like there's nothing to be found regarding Casandra's plot bugs in the map file, so I have to keep looking in the lua files.

It seems at first that `progress.foundmayor > 0` is true when you first enter town2/Randen but it's actually `== 0`. I found out by adding `bubble(en, _"foundmayor == " .. progress.foundmayor)` before `LOC_join_casandra(en)`: http://i.imgur.com/tWy4a8T.jpg
Nearly as good as if `print(progress.foundmayor)` worked.

So it comes back to `set_ent_id(13, CASANDRA)` and `set_ent_active(13, 0)`.

`set_ent_active(13, 0)` removes (deactivates?) the entity with ID 13 from the map. I can neither collide nor interact with it.
`set_ent_active(13, 1)` re-adds (activates?) the entity with ID 13 to the map after running above command first. I can interact as usual.

As far as I can tell, `mapdraw` doesn't control whether an entity is active or not. So all we have to do is make it default that entity 13 is disabled by moving `set_ent_active(13, 0)` to right before `if progress.foundmayor > 0 then` and adding `set_ent_active(13, 1)` right before `set_ent_id(13, CASANDRA)` (which as I realized corrects her clothes).

Now she does not appear in Randen unless mayor has been freed and she hasn't joined the team or roster yet.

http://codepad.org/SJEHMwRq

**Comment by peterhull90** [comment]
It used to be possible to call up a 'console' by pressing the '\' key. In the console you can call functions, set values and view values (IIRC if you enter 'return x' it will print the value of x).

The console is only compiled in when DEBUGMODE is enabled, not sure how this is done with the cmake scripts.
