### ISSUE TITLE
Crash on first visit to Temple north of Andra

### ISSUE THREAD

**Issue by qubodup** [grrk-bzzt/kq-fork#24]
When I first enter the temple, I get this error and kq crashes.

<pre>PANIC: unprotected error in call to Lua API ([string "./scripts/temple1.lua"]:28: attempt to call global 'int' (a nil value))</pre>

I added a print statement into the file to find out what value the variable has at that moment but that didn't work. print("test") has no effect either.

You can see the crash at the end of http://youtu.be/W0Z-q12Gpj4

**Comment by qubodup** [comment]
I have split the first if condition into two and found that `not LOC_manor_or_party(TEMMIN)` does not cause the crash but `get_progress(P_TALK_TEMMIN) == 3` does.

It seems like bridge, bridge2, town1, town2, town3, cave1, cave2, manor - probably all locations where it doesn't crash - do not use `get_progress()` at all.

I reached dville.lua and talking to an inhabitant causes a similar crash:
<pre>PANIC: unprotected error in call to Lua API ([string "./scripts/dville.lua"]:24: get_progress: Argument must be an integer.)</pre>
Same in cave3a.lua:
<pre>PANIC: unprotected error in call to Lua API ([string "./scripts/cave3a.lua"]:15: get_progress: Argument must be an integer.)</pre>

`LOC_manor_or_party` is defined in `scripts/global.lua` while `get_progress()` is defined in `src/intrface.c` line 2642 :
<pre>static int KQ_get_progress(lua_State *L)                                 
{
    // For error messages
    const char *function_name = "get_progress: ";
    if (lua_isnumber(L, 1))
[...]</pre>
`KQ_get_progress()` seems to be what happens when the Lua function `get_progress()` is executed.
(Note: I have no C experience.)

It looks to me like the C function definition might cause it to fail if the input is not int and when first entering the temple, it is null (well, nil).

Does anybody know what's up? Did C behave differently in the past or are you getting rid of the function and the scripts containing it have yet to be updated?

**Comment by peterhull90** [comment]
In the old days we used to preprocess all scripts with a file called `progress.h` which had a load of `#define P_XXX NNN` lines in it. Then `get_progress` was used with one of the `P_XXX` constants. (this is very C-like)

That file is now gone, and the current code (as far as I can see) uses `progress.xxx` instead, so it should say `progress.talk_temmin`, not get_progress(P_TALK_TEMMIN).

I think maybe the changeover is not complete and there are still some uses of `get_progress` still around.

**Comment by qubodup** [comment]
Thanks,
It turns out the variables already exist in global.lua and the map files just have to be fixed.
templ1.lua for example: http://codepad.org/FD4DrweL

I can go through all level files and make the changes. How should I provide the fixes? You could give me write access or I could provide diffs or end results in a zip with the changed files.

**Comment by OnlineCop** [comment]
As this is grrk-bzzt's repo, it may be best to fork the project, and then submit a pull request. We'll merge in your changes.

**Comment by qubodup** [comment]
Thanks, grrk-bzzt was so kind to give me write access.

It seems like a 3-step sed command was able to take care of "porting" to the new variable style. https://gist.github.com/qubodup/7ad4baa98aec1d7adf7d I checked a few locations only http://youtu.be/aUQZuA1aicE
