### ISSUE TITLE
Plot Bug with Casandra in Randen

### ISSUE THREAD

**Issue by qubodup** [grrk-bzzt/kq-fork#25]
When you first arrive in Randen, Casandra awaits, saying something about you having rescued her(?) and offering to join.

If you let her join and return to the city, she will still be there, offering to join.

Arrival: https://youtu.be/QW7-I1Ak6Gg?t=46m49s
Re-entry: https://www.youtube.com/watch?v=XMzbJwg2yYg

This seems to be related to `scripts/town2.lua`, the `sidequest2` variable and `en == 13`, making Casandra be present.

The strange thing is that Ajathar doesn't re-appear near the tunnel/cave entrance but Casandra does.

**Comment by OnlineCop** [comment]
To be honest, most of the plot development (and map editor and Lua scripting) was done by my sister and/or Peter Hull before I joined the kqlives project (however long ago that was). I have no idea about what their plans were for the plot, how things were to play out, etc.

I know that TeamTerradactyl had created about a dozen new towns, as well as a castle where Malkaron would be found and fought, and then started to break each of the "supporting characters" apart from the main storyline so acquiring any of those 6-7 others required that you finish side quests before they'd join you.

Casandra, for example, was captured along with the mayor. You leave Randen, head south to a small patch of trees, and save her along with the Mayor. That's when she's supposed to appear in town, offering to join your party. There seems like some logic problems (as far as whether you had actually completed that mission) are showing up, so we'll need to rewrite it.

Honestly, I don't really know much about ANY of the overarching storyline. From what I knew, the storyline itself was incomplete, and then developers lost interest in the project and the whole thing just ground to a halt.

I'm all for someone taking over the new storyline. The map editor appears to still function (it's very shortcut-based, so you need to use the F1/Help screen a lot to figure out how to do stuff), although I would _like_ to replace that map system entirely and go with another option, such as the TMX (Tiled map editor) format.

But the storyline can be written almost entirely map-format agnostic.

**Comment by qubodup** [comment]
I also just realized this is a duplicate of #21  - my bad!

If the previous authors' intentions aren't documented or can't be found out, the game needs to be playable or the plot documented, so fixing the existing plot is probably a priority before being able to continue the existing plot.

I will close this as invalid (duplicate) and will try to figure out how to solve the bug in #21
