### ISSUE TITLE
Programming language C or C++

### ISSUE THREAD

**Issue by peterhull90** [grrk-bzzt/kq-fork#34]
I noticed that there is a branch where the code has been converted to C++ but this has fallen behind master recently. Is the intention to switch to C++ at some point? Personally I would support this because I find implementing lists, maps etc a bit of a pain in C; using the STL containers is easier/less error prone. I wouldn't be in favour of a wholescale 'convert everything to classes' rewrite though.

**Comment by OnlineCop** [comment]
I don't mind converting it to C++ at all. It opens up all sorts of possibilities (some libraries that we would want to use are better suited to C++ than C).

1. Does anyone NOT want it converted to C++?
2. Is there someone who can test the various aspects of the game and/or engine to test that converting doesn't break things?
3. Is there any Unit Test framework that we want to add? It's not necessary, but vastly easier to do in C++ than C, and will let us ensure that future changes won't break things unexpectedly.
4. Do we need all platforms to be converted (so far, we only have `unix.c` but have not versioned `windows.c` or `osx.c` (or was it `mac.c`?), so if we want it cross-platform and those are the only files that need to be customized, does someone have a platform set up that would be able to test that we converted the C-to-C++ correctly?

I found that it took about a day's work to get everything converted. With the "remove all warnings" ticket done, this may even go faster than that. I may even be able to use much of the already-converted-to-c++ code that help move things along.

Changing just the filename extensions from `.c` to `.cpp` and taking care of immediate warnings/errors isn't that bad. But we probably want to convert all the `sprintf()` instances into STL string manipulations.

**Comment by uncleshelby** [comment]
My opinion probably doesn't matter much, but I'd love to see this project switch to C++. I recently started digging up information about this game, since I played it back in the late 2000s. I'm also learning C++ (still a total beginner) and SDL (also a beginner) and would love to help with this project.

**Comment by peterhull90** [comment]
The key question is, "will this make the game better?"

I found it difficult to work on modifying/extending the game, partly because of the way data is scattered across various global tables. If we took a hard look at what data there is, and what belongs with what, we could come up with a more logical model. But this would require more complicated data structures, and hence a robust container library would make our lives easier. Hence, C++. That's my train of thought anyway.

**Comment by peterhull90** [comment]
@uncleshelby help always needed!
@OnlineCop I do have access to Windows and Mac, and Linux via VirtualBox, so should be able to test all three platforms.

**Comment by uncleshelby** [comment]
@peterhull90 What version of Windows do you have? I've got Windows 7 Enterprise, so at the very least I could help with testing if no one else is on Windows 7.

**Comment by OnlineCop** [comment]
I'm on a Mac, but I can probably load up KQ onto my work computer running
Windows 7 and Visual Studio. I just need to figure out how to set up
Allegro, Dumb, and Lua for the project.

**Comment by OnlineCop** [comment]
Commit hash 18a6918529d6bb6d8c04fb8ae259c283d080f46e is in the new
c_plus_plus branch. It compiles and runs on my ArchLinux setup, although I
have not tested everything.

I'd like some of the structs, like `s_fighter`, to be converted into full
C++ objects. Class methods over static functions would be ideal.

**Comment by peterhull90** [comment]
Compiles OK under Ubuntu using either clang or gcc. Not tried Windows yet. Looking good.

**Comment by peterhull90** [comment]
Found a couple more things for Visual Studio, see pull request #35 

Then I think it's OK to merge this with master (working with a non-master branch on github is a bit of a pain, I have found)

**Comment by peterhull90** [comment]
> I'd like some of the structs, like `s_fighter`, to be converted into full C++ objects.

Maybe take that slowly and convert as and when you touch that code? Ideally we'd avoid that kind of rolling knock on effect where a small change in one place has effects far and wide (said from bitter experience!!)

**Comment by peterhull90** [comment]
OK, what's next?

**Comment by OnlineCop** [comment]
Unless there are objections, I think the *c_plus_plus* branch looks stable enough that it can be merged into *master*. Most development going forward will probably be C++ anyway, and maintaining both a C and a C++ branch would be pointless.

Can the current c_plus_plus version be run on a few different platforms to ensure that nothing got broken? If everything looks clean, I'll try to merge to master in a few days.

**Comment by uncleshelby** [comment]
I'm in favor of merging *c_plus_plus* into *master*. It successfully compiled and ran for me on Linux Mint 17.2, although I did notice this bug: https://github.com/grrk-bzzt/kq-fork/issues/43

**Comment by peterhull90** [comment]
> looks stable enough that it can be merged into master

I agree.

**Comment by OnlineCop** [comment]
The *c_plus_plus* branch has been merged into *master*.
