### ISSUE TITLE
Typo in draw.c

### ISSUE THREAD

**Issue by peterhull90** [grrk-bzzt/kq-fork#42]
Just spotted this whilst doing something else, I think the '10' should be '1000' or maybe just drop the condition altogether?
https://github.com/grrk-bzzt/kq-fork/blob/master/src/draw.c#L641
https://github.com/grrk-bzzt/kq-fork/blob/master/src/draw.c#L665

**Comment by OnlineCop** [comment]
Yes, all those `10` should be `1000`. I really hate that particular function. So much hard-coding, like `    xofs = 16 - (dx & 15);` where it takes the `dx` value, chops off all bits above 15, then assigns that to `xofs`. That 16 is most likely the TILE_W, so if that value changes, that whole "offset the camera" code should be rewritten.

That would mean that this debugging "zone number" code that you found would either need to be drawn a different way so Tiled can render it (if/when we move to that), or we'll have to scale that number if TILE_W is no longer 16 pixels (32-pixel tiles wouldn't need to wrap the number like this, so this logic would become moot, but 12-pixel or another-width tile set would require something else).

**Comment by peterhull90** [comment]
I wrote a script to convert `.map` files to `.tmx` for tiled a while back. I exported the zones as rectangular objects in an object layer rather than tiles (that seemed to make most sense to me at the time). The Tiled editor shows these as labelled rectangles (see image) so we could replicate that if we wanted it in the game too.
On the subject of Tiled I've done quite a bit more on that, and have an exciting experimental branch for you to look at (or at least more exciting that the emacs variable one :zzz: )

![town1](https://cloud.githubusercontent.com/assets/376711/12514826/3efc28a4-c11d-11e5-9410-5aee2d420b5e.jpg)

**Comment by OnlineCop** [comment]
How much effort does it look like it will take to convert KQ over to using Tiled? Now that this is in C++, it should be significantly more flexible, although there is still a lot of hard-coded values that would have to be torn out.

**Comment by peterhull90** [comment]
I made a comment on issue #12

**Comment by OnlineCop** [comment]
Moving to TMX format, this issue is no longer relevant.
