### ISSUE TITLE
Detail steps required to build on Windows

### ISSUE THREAD

**Issue by OnlineCop** [grrk-bzzt/kq-fork#57]
Several dependencies are required to get KQ to build on Windows, and if we could list the required steps, from ground zero to finish, that it would take to compile, it would be very useful.

- MS Visual Studio Community edition is free, and widely supported.
- Allegro4 may be easy to set up, although many of the online documentation are for MSVC 5 or 6, and may need some updates
- Dumb, TinyXML2 and Lua, if I'm not mistaken, only require a few source files to be dropped into the project directly without the need to build a library for them first. If that's the case, give steps!

It might even be useful if a "shell" project could be created and zipped, which would contain most of the files, where the only remaining tasks would be to clone the **kq-fork** repo into it.

Thoughts? Or would be be better to just list the steps and let the developers download and run it all themselves?

**Comment by peterhull90** [comment]
I've been building on Windows for a while so I can write down the steps I took. I did try making a 'library package' but it turned out to be quite tricky (can't remember exactly why, I think it was to do with absolute vs relative paths)

**Comment by OnlineCop** [comment]
Does the Windows build need things like `zlib` and `libpng`?

**Comment by OnlineCop** [comment]
http://www.programming4beginners.com/tutorial/allegro/installing-the-allegro-library talks about _Microsoft Visual Studio 2013/2015_ and using Allegro 4.4. It might be worth a shot to at least get parts of the system setup properly for Allegro 4.

**Comment by OnlineCop** [comment]
Just added https://github.com/grrk-bzzt/kq-fork/blob/master/INSTALL_msvc.txt although I haven't fully figured out what I need to do in order to get DUMB and some of the other files to compile.

It's possible that we don't need to compile those projects at all, and we can simply drop in certain files into the project as-is.

@peterhull90 or others who have KQ able to build successfully on your systems: Can you think of which steps should be performed? I'd like to have some steps generic enough that anyone starting from scratch could get up and running, even if it does require a hack like including those files directly in the `src/` and `include/` directories.

**Comment by peterhull90** [comment]
I've tried various methods. All were painful. I have now got a zip file with all the dependencies (headers and libraries) and a VS2015 project which references them. The CMake file in principle could do it but it's got some problems for Windows at the moment. Can I send you the zip file so you can give it a try? Instructions should be:
1. unzip file into kq-fork directory
2. open Solution file in VS
3. That's it.

**Comment by OnlineCop** [comment]
Sure, fire that on over to me. You can meet up with me in chat (#kqfork on freenode), or email if you want. Or dump the .zip file in github or something.

**Comment by OnlineCop** [comment]
Pushed up @peterhull90's solution file, as well as some minor additions of my own, so Visual Studio can compile the project very close to out-of-the-box.
