### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by z9484** [grrk-bzzt/kq-fork#73]
It would be cool to get to a 1.0 release before the 20th anniversary of kqlives September 2022.  Well at least going off the sourceforge changelog history.

I finished Ayla's quest, added Sarina's quest(its a bit lame, sorry) and added in some ending(s). I cut out the AirTank and replaced it with a magic trident but followed the outlined plot at least roughly.
I also replaced most of the enemy graphics with those from Dungeon Crawl 32x32 Tiles. I kept some (the dragons and giants) that seemed to be original, if you find that's not the case you can let me know.

You can check it out at 
https://github.com/OnlineCop/kq-fork/tree/road_to_1.0

Stuff left to do: (Mirrored from https://github.com/OnlineCop/kq-fork/wiki/Road-to-1.0)
- Doom and all Death spells don't appear to work anymore (The idea was that opal armor when the staff is nearby gives you immunity to everything except Death spells but as they aren't working right now I didn't reduce magic damage)
- Set up zone 0 combat for cave6a, cave6b, cave9, pass2 and main map combats for zones 86-90  (I added  8 more sprites after the dreadpede that could be used. The rat looking guy was an idea for the boss at the end of cave6b where you get the trident).  -- Mostly done
- Encounters especially the new ones I made could use a balance pass
- Change character graphics I was leaning towards https://opengameart.org/content/18x20-characters-walkattackcast-spritesheet but that requires modifying the engine to support slightly bigger sprites
- Add in a scene where if Ayla is in your party and Nostik has left the manor you can break into his room and find a mysterious letter from "M" (Malkaron)
- Check for bugs (the coliseum has some edge cases that might show up)
- Change tile graphics
- Change music not created by Josh's cousin as outlined in the sourceforge posts as outlined on the wiki page

**Comment by pedro-w** [comment]
Z - this is great! I have dusted off the code and I'm going to finish  the SDL2 conversion. It's going well so far, I'll let you know

**Comment by pedro-w** [comment]
SDL2 conversion is done, though I expect there may be a few rough corners. I will put a PR in imminently but beware, it is a pretty intrusive set of changes. However I didn't need to change the scripts or maps at all.

**Comment by pedro-w** [comment]
Please see #74

**Comment by z9484** [comment]
Nice work. I've been working on adding in the rest of the combats so I need to play through it without cheating to make sure the balance is right. I might as well do that with this new branch. Unfortunately I'm having some trouble getting the cmake to build the project on windows. I keep getting a No package 'SDL2_mixer' found. Argh C++ libraries are such a nightmare on windows.

**Comment by pedro-w** [comment]
I don't have a Windows system to develop on, unfortunately. SDL_mixer is a separate download so I guess you need the 'Development Libraries' from https://www.libsdl.org/projects/SDL_mixer/ and stick them in the same place as SDL is on your system. There is a comprehensive FindSDL.cmake that comes with CMake but no corresponding one for SDL_mixer, maybe we need to copy and adapt it?

**Comment by OnlineCop** [comment]
I have a Win10 system and have been looking into setting up SDL2 within it, for use with KQ specifically, like I did with the Allegro4 and Lua libraries earlier. If I can get it to compile properly, I should be able to write it in the wiki.

Sorry for the delayed response; working two 40 hr/week jobs since December, and free time has been difficult to come by.

**Comment by pedro-w** [comment]
I am making some progress on this using Visual Studio and vcpkg but gosh it's like pushing treacle ... uphill. I'm not a big fan of cmake.

**Comment by z9484** [comment]
I think line 6-7 of CMakeLists.txt should be `list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})` so as not to overwrite the default module path which is where FindLua can be found. Unfortunately now FindLua cant find lua even though its in the deps folder. I also noticed using relative paths with the helper vars like SDL2_DIR=../SDL2 for example does not work, it must be absolute.

**Comment by pedro-w** [comment]
![image](https://user-images.githubusercontent.com/22172519/172041072-c1ad7962-3cf6-4fad-bc94-4fc4201608b9.png)
Getting there ... need to check now that the changes I made for Visual studio didn't mess up every other platform

**Comment by OnlineCop** [comment]
As you get SDL2 (and/or Visual Studio) working, would you consider writing down your steps/process on the [SDK Rework](https://github.com/OnlineCop/kq-fork/wiki/EngineRework) wiki?

The [KQ with Allegro 4: VS2019](https://github.com/OnlineCop/kq-fork/wiki/KQ-compiled-with-Allegro-4:-Visual-Studio-2019) was a bit of a stream-of-thought, although I was able to reproduce my steps at least one other time from them, so if nothing else, they were a good "here, future me: try to get it to work again!" for myself.

For example: if you installed and compiled SDL2 from sources on Windows, and you got KQ working, then that's 100% fine. I'd rather have a "well, I could do that but rather not" that actually works, than "I want to do it this other way" that doesn't work. We can always clean up the build process once the engine and game are finished.

I'm surprisingly excited about working on KQ again. I often get distracted by work/life, but when I see others' enthusiasm, it's rather contagious.

**Comment by OnlineCop** [comment]
Big question: Should I just give all of you write access to this repo? I might protect the `master` branch (should I do what others are doing and rename it to `main`?) so it only accepts reviewed Pull Requests (maybe 1 required reviewer and any number of optional ones, in case some of us are too busy to quickly look over changes)?

Then we could do full development off of `dev` or `road-to-1.0` and accept that those branches can break at any time and the `master`/`main` branch should always be stable?

**Comment by z9484** [comment]
Hmm either way but this is following the github fork model. I was going to merge #74 into road-to-1.0 once I can get it to compile for me and make sure there's not any game breaking bugs. Then when we decide we are ready for a release we can merge road-to-1.0 into master.

**Comment by pedro-w** [comment]
I do now have the same CMakeLists.txt working on Windows + VCPKG and MacOS + Homebrew. All the dependencies were OK apart from SDL_mixer which does have CMake package in vcpkg but not brew so I had to put some conditional code for that. I think the best bet is for me to add the changes to the PR now because it's holding Z up and then someone more skilled in CMake can tell me how it should be done properly. Does that make sense?

**Comment by z9484** [comment]
I've never heard of VCPKG. It looks interesting. I got it to get past the find package steps with it but its still giving me unresolved externals with _SDL_main and the kqres functions for some reason. 
Whats M_LIB? It looks like its linked but I don't see a find package in the cmake for it.

**Comment by pedro-w** [comment]
> Whats M_LIB? It looks like its linked but I don't see a find package in the cmake for it.

I guess it's related to the math library. If I remember correctly, for C some platforms need you to explicitly link it in and some don't, but for C++ it always is and so M_LIB probably is no longer set by anything in the CMake file.
(however that might be true only for GCC, I'm not sure)

**Comment by OnlineCop** [comment]
Is it safe to delete the following:
1. The entire `deps/` directory (old `include/` and `libs/` files)
2. `src/music.cpp` (as we now use `src/music_mix.cpp`) OR simply replace the former with the latter
3. `src/music_dumb.cpp` (removed DUMB)
4. `saves/sgupdate.c` (was used to update older versions, but the current version is likely incompatible)

We appear to have duplicates of the .png files under the `data/`, `maps/` and `other/source-images/` folders, but we can leave those images for now.

**Comment by OnlineCop** [comment]
Is it safe to delete `kqsnd`?
- `data/kqsnd.dat`
- `include/kqsnd.h`

There's a comment within `src/setup.cpp` above the `load_samples()` function mentioning the `kqsnd.h` header, but it is no longer referenced as that was something Allegro 4's grabber tool auto-generated.

**Comment by OnlineCop** [comment]
Regarding the above two comments: PR #82 removes these files as I can't see anywhere in this branch where they're used.

I tried adding @pedro-w as a reviewer, but that doesn't appear to let me. I tried re-sending an invite, mainly so I can get your set of eyes on PRs, if you're interested.

OR... I can make changes directly into the repo and pretend that I'm certain that my changes won't break all the things. I can move the conversation for deleting those files into the PR thread, so we don't fill up this issue with unnecessary chatter.

**Comment by OnlineCop** [comment]
1. Should the `road_to_1.0` branch be made the default branch instead of `master`?
2. Should work on `road_to_1.0` be merged into `master`?
3. Should we follow the industry standard and rename `master` to `main`?
4. Should we rename `road_to_1.0` to `main` and leave `master` where it is?
5. Should we rename `road_to_1.0` to `dev`, set it to default, and either leave `master` named `master` or change it to `main`?

In a typical work environment, I've seen `main` (or `master`) used as the branch that releases are based off, with only bug fixes cherry-picked into it. The `main` branch is typically locked so you can't push directly onto it; changes require a PR to be approved by one other team member before it can be merged in.

And then `dev` is where all the active work is done where code may be unstable and things may break.

I don't know if we want to be that restrictive, but I'd really like to see PRs default to merging into the work branch (`road_to_1.0`  or `dev` or whatever we name it) instead of telling me that it's "X commits ahead and Y commits behind" each time.

**Comment by z9484** [comment]
I don't see a reason to change it from the normal gitflow model. master maintains release history and that's it.  Feature development is branched off a develop branch until a release is ready and then it is merged into master. I created road_to_1.0 because it changed almost all the enemy graphics. So if that change wasn't approved it wouldn't go straight into develop(Not that a develop branch even exists that I could have pushed to). But currently it is the defacto develop branch so it can be renamed as such if you want. And it should be set as the default branch to work out of.

**Comment by OnlineCop** [comment]
Alright; the default should now be `road_to_1.0`. I don't know how this affects your local repos, as I haven't seen this done before.

**Comment by z9484** [comment]
the local change would be if you do a fresh clone it should go to road_to_1.0

**Comment by z9484** [comment]
Initial balance done in #110. We should create new tickets for anything left.
