### ISSUE TITLE
Remapping keys inside Options: needs debounce

### ISSUE THREAD

**Issue by OnlineCop** [grrk-bzzt/kq-fork#77]
Related to #75, in the configuration screen to change the keyboard inputs, the default keys for Cancel and Accept are CTRL and ALT, respectively.

When you select one of the options to remap and hit Accept to begin to scan for the new keyboard input, there is no wait for the Accept button to be released before the new key is read in.

There needs to be a delay before the new key is read in, or else listen for the release event for whichever button is currently set for Accept. Only then, it should read in the new key for the selected option.

**Comment by pedro-w** [comment]
I think this can be closed now that #85 is merged
