### ISSUE TITLE
Windows 10 + Visual Studio 2022 setup

### ISSUE THREAD

**Issue by OnlineCop** [grrk-bzzt/kq-fork#78]
I finally got Visual Studio set up where KQ compiles *and* runs. I've pushed these changes to [dev/onlinecop/vs2022](https://github.com/OnlineCop/kq-fork/tree/dev/onlinecop/vs2022).

1. I believe I had a bug in one of my VS2019 plugins (unrelated to KQ), causing it to crash.
2. I downloaded Visual Studio Community 2022 using the Visual Studio Installer, and selected:
    - `Desktop development with C++`
    - `Game development with Unity` (probably not required for your setup)
    - `Game development with C++` (may also not be required for your setup)
    - `Linux and embedded development with C++` (probably not required for your setup)
3. Taking advice on #74, as well as the updates on the [EngineRework](https://github.com/OnlineCop/kq-fork/wiki/EngineRework#building-on-windows-with-new-sdl-branch-on-road_to_10) wiki page, I made the following system and repo changes:
    1. I installed vcpkg to `C:\Users\user\source\repos\vcpkg` according to its [Getting Started](https://vcpkg.io/en/getting-started.html) guide for Windows.
    2. I added @z9484's `vcpkg.json` file to the project:
        ```json
        {
            "name": "kq",
            "version-string": "0.99",
            "dependencies": [
                "pkgconf",
                "sdl2",
                "sdl2-mixer",
                "lua",
                "libpng",
                "zlib",
                "tinyxml2"
            ]
        }
        ```
    3. I only had to modify one line in `CMakeSettings.json`:
        - From: `"cmakeToolchain": "C:/Users/`**`Peter`**`/Source/Repos/vcpkg/scripts/buildsystems/vcpkg.cmake"`
        - To: `"cmakeToolchain": "C:/Users/`**`user`**`/Source/Repos/vcpkg/scripts/buildsystems/vcpkg.cmake"`
    4. I removed one line in `CMakeLists.txt`:
        - Line 2: `include(FindPkgConfig)`
    5. I ran  `vcpkg.exe install` from within the `kq-fork/` root directory, which installed packages under `vcpkg_installed/`.
    6. Within VS2022, I opened the `C:\Users\user\Source\Repos\kq-fork` directory:
        1. I selected Build->Build All
        2. When the build completed, from the terminal in the `kq-fork` root, I ran: `out/build/x64-Debug/kq-fork.exe`
        3. The game runs!

I plan to modify this Issue as I create a fresh Windows user account and reinstall the various components, to ensure some undocumented steps didn't come into play here.

This issue was also created to facilitate discussions for anyone wishing to ask/answer questions specific to getting KQ to run on Windows + VS2022 (the wiki doesn't appear to have an easy way to discuss stuff).

**Comment by OnlineCop** [comment]
As an aside, I've had my IRC bouncer parked in the [#kqfork](https://web.libera.chat/?nick=kqfork-?&chan=#kqfork) channel for about a year now in case anyone stopped in and needed any help; I'm in the UTC-07:00 timezone, so if you talk in there and I don't respond, I might be working (I currently WFH) or am AFK (maybe asleep?).

**Comment by OnlineCop** [comment]
For whatever reason, compiling from this folder builds `out/build/[Configuration]/kq-fork.exe`, but running from that directory causes the game to error because it looks for the maps and other data files relative to the launch directory.

    DEBUG: Cannot load bitmap 'misc.png'
    DEBUG: Error loading image.

If I launch from the kq-fork root, it runs fine.

I've got to find out how to set VS2022's run-from path to point to the root...

**Comment by z9484** [comment]
You can modify that by changing the KQ_DATADIR cmake variable

**Comment by pedro-w** [comment]
The KQ_DATADIR is an interim measure. What I mean is that when KQ is finished(!) and installed in its proper (platform specific) location, SDL knows how to find the data relative to the executable and KQ_DATADIR can be left undefined. But during development it's convenient to build the exe whereever and use KQ_DATADIR to point to the data, as z9484 says.
(note this doesn't apply to linux; when we get to it we'll have to define it in terms of the 'install prefix')

**Comment by pedro-w** [comment]
@OnlineCop  and @z9484 , if you have time please can you check out #76 ? I hope that will be the holy grail of getting a CMakeLists.txt that'll work without modification on Win, Mac and Linux.

The `cmakeToolchain` shouldn't have been checked into CMakeSettings.json (especially not with a hardcoded path), that was my mistake. Visual Studio AFAICS can find the file without any setting; it may rely on vcpkg being in its default location or possibly `vcpkg integrate install` sets something in the registry. For generating via the command line I believe you still need `-DCMAKE_TOOLCHAIN_FILE=YOUR PATH/vcpkg/scripts/buildsystems/vcpkg.cmake` as mentioned in [the wiki](https://github.com/OnlineCop/kq-fork/wiki/EngineRework#building-on-windows-with-new-sdl-branch-on-road_to_10)

**Comment by OnlineCop** [comment]
@pedro-w: I checked out #76 earlier today; cmake now errors with the SDL2 stuff, so I can't get it to compile/build anymore. I left a note in that PR.

I can go ahead and merge it in, but I hope I can figure out what I'm doing wrong so I can continue work on the project.

**Comment by pedro-w** [comment]
No don't merge, I've just seen your comment on #76. It did work for me.
Aiiieee! Back to the drawing board

**Comment by OnlineCop** [comment]
Did you perhaps install SDL2 differently than described on EngineRework?

**Comment by pedro-w** [comment]
Maybe. I did what Z calls "global vcpkg installs" i.e. from the vcpkg command line. Just checking, did you delete and re-create the build directory, sometimes it seems CMake can't cope if you do something radical to the configuration.

**Comment by OnlineCop** [comment]
From the [vcpkg Getting Started](https://vcpkg.io/en/getting-started.html) notes within the Windows tab:

> ## Install vcpkg
> Installing vcpkg is a two-step process: first, clone the repo, then run the bootstrapping script to produce the vcpkg binary. The repo can be cloned anywhere, and will include the vcpkg binary after bootstrapping as well as any libraries that are installed from the command line. It is recommended to clone vcpkg as a submodule for CMake projects, but to install it globally for MSBuild projects.

Let's say that I plan to only develop kq-fork with Visual Studio 2022: it sounds like I'd want to install vcpkg globally somewhere (so my C:\Users\user\source\repos\vcpkg directory should probably be fine).

But if I plan to additionally use another editor/compiler, I should plan to use the CMake solution instead? Or in addition?

Because if I read that correctly, for the CMake solution, it suggests that it's cloned under the `kq-fork` repo:

    /c/Users/user/source/repos/kq-fork$ git clone https://github.com/Microsoft/vcpkg.git

Is that how you're reading that?

**Comment by OnlineCop** [comment]
Let's see if I've done this correctly:

1. Using Git Bash (so I don't accidentally trigger the WSL2 layer) in `/c/Users/user/source/repos/`:
    ```bash
    git clone -b road_to_1.0 git@github.com:OnlineCop/kq-fork.git kq-fork-2
    ```
2. Within `/c/Users/user/source/repos/kq-fork-2/`, pull in PR #76:
    ```bash
    ~/source/repos/kq-fork-2 [road_to_1.0]$ git fetch origin pull/76/head:pedro-pr-76
    remote: Enumerating objects: 4, done.
    remote: Counting objects: 100% (4/4), done.
    remote: Total 4 (delta 3), reused 3 (delta 3), pack-reused 0
    Unpacking objects: 100% (4/4), 798 bytes | 31.00 KiB/s, done.
    From github.com:OnlineCop/kq-fork
     * [new ref]         refs/pull/76/head -> pedro-pr-76
    ```
3. Switch to that branch:
    ```bash
    ~/source/repos/kq-fork-2 [road_to_1.0]$ git checkout pedro-pr-76
    Switched to branch 'pedro-pr-76'

    ~/source/repos/kq-fork-2 [pedro-pr-76]$
    ```
4. Run cmake, assuming `vcpkg` is located in a sibling directory:
    ```bash
    ~/source/repos/kq-fork-2 [pedro-pr-76]$ cmake -B build -S . -DKQ_DATADIR="$PWD" -DCMAKE_TOOLCHAIN_FILE="$PWD"/../vcpkg/scripts/buildsystems/vcpkg.cmake
    ```
    (I realize the `"$PWD"` may be overkill, but it was giving me odd runtime behavior when I used `.` as the current directory in earlier runs.)

    When I do this, it fails to find LUA_LIBRARIES (it might fail to find the other libraries after that as well, but it always stops on the first missing library):

    ```
    -- Building for: Visual Studio 17 2022
    -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
    -- The C compiler identification is MSVC 19.32.31329.0
    -- The CXX compiler identification is MSVC 19.32.31329.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
    Call Stack (most recent call first):
      C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
      C:/Program Files/CMake/share/cmake-3.22/Modules/FindLua.cmake:233 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      C:/Users/user/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
      CMakeLists.txt:9 (find_package)


    -- Configuring incomplete, errors occurred!
    See also "C:/Users/user/source/repos/kq-fork-2/build/CMakeFiles/CMakeOutput.log".
    ```
5. Re-running it but with the full path instead of `"$PWD"` for the sibling directory yields pretty much the same:
    ```bash
    ~/source/repos/kq-fork-2 [pedro-pr-76]$ cmake -B build -S . -DKQ_DATADIR="$PWD" -DCMAKE_TOOLCHAIN_FILE=/c/Users/user/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake
    -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
    CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
    Call Stack (most recent call first):
      C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
      C:/Program Files/CMake/share/cmake-3.22/Modules/FindLua.cmake:233 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      C:/Users/user/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
      CMakeLists.txt:9 (find_package)


    -- Configuring incomplete, errors occurred!
    See also "C:/Users/user/source/repos/kq-fork-2/build/CMakeFiles/CMakeOutput.log".
    ````

**Comment by pedro-w** [comment]
I did this from git bash:
```
git clone -b road_to_1.0 https://github.com/OnlineCop/kq-fork kq-fork-2
cd kq-fork-2/
git fetch origin pull/76/head
git merge FETCH_HEAD
git commit -m"Merged"
cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=/c/Users/Peter/Source/Repos/vcpkg/scripts/buildsystems/vcpkg.cmake
```
Main difference is I merged from #76 instead of checking it out. (I git cloned from your fork so I had to use https:// obviously)
also check what you've installed in vcpkg using `vcpkg list`, I've got:
```
libpng:x64-windows                                 1.6.37#17        libpng is a library implementing an interface fo...
libpng:x86-windows                                 1.6.37#17        libpng is a library implementing an interface fo...
lua:x64-windows                                    5.4.4#2          A powerful, fast, lightweight, embeddable script...
lua:x86-windows                                    5.4.4#2          A powerful, fast, lightweight, embeddable script...
sdl2-mixer:x64-windows                             2.0.4#16         Multi-channel audio mixer library for SDL.
sdl2-mixer:x86-windows                             2.0.4#16         Multi-channel audio mixer library for SDL.
sdl2-mixer[nativemidi]:x64-windows                                  Support for MIDI audio format on Windows and macOS.
sdl2-mixer[nativemidi]:x86-windows                                  Support for MIDI audio format on Windows and macOS.
sdl2:x64-windows                                   2.0.22#1         Simple DirectMedia Layer is a cross-platform dev...
sdl2:x86-windows                                   2.0.22#1         Simple DirectMedia Layer is a cross-platform dev...
tinyxml2:x64-windows                               9.0.0#1          A simple, small, efficient, C++ XML parser
tinyxml2:x86-windows                               9.0.0#1          A simple, small, efficient, C++ XML parser
vcpkg-cmake-config:x64-windows                     2022-02-06
vcpkg-cmake:x64-windows                            2022-05-10
zlib:x64-windows                                   1.2.12#1         A compression library
zlib:x86-windows                                   1.2.12#1         A compression library

```
(I installed 64 and 32 bit libraries though I think cmake defaults to 64 these days?)

**Comment by OnlineCop** [comment]
From `vcpkg list`, I have:

    $ vcpkg list
    libpng:x86-windows                                 1.6.37#17        libpng is a library implementing an interface fo...
    lua:x86-windows                                    5.4.4#2          A powerful, fast, lightweight, embeddable script...
    pkgconf:x86-windows                                1.8.0#3          pkgconf is a program which helps to configure co...
    sdl2-mixer:x86-windows                             2.0.4#16         Multi-channel audio mixer library for SDL.
    sdl2-mixer[nativemidi]:x86-windows                                  Support for MIDI audio format on Windows and macOS.
    sdl2:x64-windows                                   2.0.22#1         Simple DirectMedia Layer is a cross-platform dev...
    sdl2:x86-windows                                   2.0.22#1         Simple DirectMedia Layer is a cross-platform dev...
    tinyxml2:x86-windows                               9.0.0#1          A simple, small, efficient, C++ XML parser
    vcpkg-cmake-config:x64-windows                     2022-02-06#1
    vcpkg-cmake:x64-windows                            2022-05-10#1
    vcpkg-tool-meson:x64-windows                       0.62.1           Meson build system
    zlib:x86-windows                                   1.2.12#1         A compression library

That's probably my issue then: lua is installed as x86 for some reason, and when I run cmake in the directory, it claims it can't find it:

    $ cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=/c/Users/user/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake
    -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
    CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
    Call Stack (most recent call first):
      C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
      C:/Program Files/CMake/share/cmake-3.22/Modules/FindLua.cmake:233 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      C:/Users/user/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
      CMakeLists.txt:9 (find_package)

**Comment by OnlineCop** [comment]
```bash
$ vcpkg install --triplet x64-windows libpng lua sdl2 sdl2-mixer tinyxml2 zlib
```
followed by
```bash
$ cmake -S . -B build -DKQ_DATADIR="$PWD" -DCMAKE_TOOLCHAIN_FILE=/c/Users/user/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake
```
seems to have been what I needed: it didn't like the mix of 32- and 64-bit packages.

It compiled fine in VS2022, but hit a runtime error on launch because it couldn't find one of the images. Modifying `CMakeSettings.json` showed that `KQ_DATADIR` was still set to `.` for some reason instead of `$PWD`. I manually set it to the `C:/Users/user/source/repos/kq-fork-2/` path, and I was able to compile and play directly.

So progress!

The CMakeSettings.json diff shows:

    diff --git a/CMakeSettings.json b/CMakeSettings.json
    index 9204f06..a490260 100644
    --- a/CMakeSettings.json
    +++ b/CMakeSettings.json
    @@ -9,7 +9,8 @@
           "installRoot": "${projectDir}\\out\\install\\${name}",
           "cmakeCommandArgs": "",
           "buildCommandArgs": "",
    -      "ctestCommandArgs": ""
    +      "ctestCommandArgs": "",
    +      "variables": [{ "name": "KQ_DATADIR", "value": "C:/Users/user/source/repos/kq-fork-2", "type": "PATH" }]
         }
       ]
     }

**Comment by OnlineCop** [comment]
I deleted the directory, and followed @pedro-w's steps; it builds in VS2022 but dies at runtime (`DEBUG: Cannot load bitmap 'misc.png'`).

I deleted the directory and followed the same steps again, except I changed the `cmake` step to define the KQ_DATADIR directory:

     cmake -S . -B build -DKQ_DATADIR="$PWD" -DCMAKE_TOOLCHAIN_FILE="$PWD"/../vcpkg/scripts/buildsystems/vcpkg.cmake

That doesn't seem to have changed anything: same result.

I deleted the directory a 3rd time, and this time modified the CMakeLists.txt file itself:

    diff --git a/CMakeLists.txt b/CMakeLists.txt
    index db7bb48..db0c359 100644
    --- a/CMakeLists.txt
    +++ b/CMakeLists.txt
    @@ -34,7 +34,7 @@ include_directories( ${LUA_INCLUDE_DIR} ${TINYXML2_INCLUDE_DIR} ${PNG_INCLUDE_DI
     add_definitions(${PNG_DEFINITIONS})
     set(KQ_DEBUGGING 1 CACHE BOOL "Features for debugging the game")
     set(KQ_CHEATS 1 CACHE BOOL "Features for allowing Lua script cheats in game")
    -set(KQ_DATADIR "." CACHE PATH "Where the data dirs are going to be installed")
    +set(KQ_DATADIR "${CMAKE_CURRENT_SOURCE_DIR}" CACHE PATH "Where the data dirs are going to be installed")
     configure_file(config.cmake.h makeconfig.h)

     set(kq-fork_SRCS

That simplified the command-line:

    cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake

At this point, VS2022 builds and runs without modifications.

So **now**, I'm going to create a brand-new Windows user account, hopefully which does not contain vcpkg (VS2022 and cmake.exe are probably global, since they're under `C:\Program Files...`, so that can't really be helped), but then run through all the installation steps again to ensure that I can write up a proper get-up-and-running README or something, and post my results here.

**Comment by OnlineCop** [comment]
1. Created new Windows user account: `kqlives` and signed in.
    - It already had VS2022 installed, and CMake was installed but not currently in Git Bash's path.

```bash
~$ [[ :"$PATH": =~ :"/c/Program Files/CMake/bin": ]] || PATH="$PATH:/c/Program Files/CMake/bin"
~$ mkdir -p ~/source/repos/
~$ cd ~/source/repos/
~/source/repos$ git clone https://github.com/Microsoft/vcpkg.git
~/source/repos$ [[ :"$PATH": =~ :"$HOME/source/repos/vcpkg": ]] || PATH="$PATH:$HOME/source/repos/vcpkg"
~/source/repos$ ./vcpkg/bootstrap-vcpkg.bat -disableMetrics
~/source/repos$ vcpkg install --triplet x64-windows libpng lua sdl2 sdl2-mixer tinyxml2 zlib
~/source/repos$ vcpkg integrate install # Without this step, I get "SDL2" error
~/source/repos$ git clone -b road_to_1.0 https://github.com/OnlineCop/kq-fork kq-fork
~/source/repos$ cd kq-fork
~/source/repos/kq-fork$ git fetch origin pull/76/head
~/source/repos/kq-fork$ git merge FETCH_HEAD
~/source/repos/kq-fork$ perl -i -pe 's@^set\(KQ_DATADIR "\K\."@\${CMAKE_CURRENT_SOURCE_DIR}"@' CMakeLists.txt
~/source/repos/kq-fork$ cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE="$(realpath "$PWD/../vcpkg/scripts/buildsystems/vcpkg.cmake")"
```
1. At this point, I opened VS2022 to `C:\Users\kqlives\source\repos\kq-fork`.
1. I selected the `kq-fork.exe` target and ran it.
     It compiled and started debugging without errors.

**Comment by pedro-w** [comment]
Can this be closed now?
