### ISSUE TITLE
Equipping Noslom with the Staff using Optimize removes all other gear

### ISSUE THREAD

**Issue by OnlineCop** [grrk-bzzt/kq-fork#96]
I believe the Staff is a two-handed item, meaning that it forbids me from equipping a shield with it.

I bought all the available weapons and armor, except the Staff, in Ekla. When I use Optimize, it fills most of the slots, with exception of Other, with a weapon, shield, helmet, armor and gloves.

After I bought the Staff and use Optimize to equip it, it clears all other slots except for Hand1, where Staff is located.

While it's fine to unequip the Hand2 item (like a shield), it shouldn't affect the other inventory.

**Comment by pedro-w** [comment]
I think it's here:
https://github.com/OnlineCop/kq-fork/blob/375936b24822442edbf4569717b97e9c0dc7d468/src/eqpmenu.cpp#L743-L746
This is called to equip slots Hand2...Arms and as soon as one fails (which, for the reason you noted, Hand2 does) the whole function finishes early.

**Comment by pedro-w** [comment]
I can reproduce this, shall I go ahead and fix it?

**Comment by OnlineCop** [comment]
Sure!

**Comment by OnlineCop** [comment]
Looks good to me. I'll let you merge it in when you're ready.

I am hoping to move everything into classes when possible, so if we need to start with some kind of KEquipmentManager or something, it might be a wrapper which is used initially to just modify the existing global variables. Over time, those globals could be migrated into the class so the values can't be externally affected.
